version: '3.5'

# https://github.com/jenkinsci/docker

services:

  jenkins:
    build: ./jenkins
    image: tutorial/jenkins:lts-alpine
    volumes:
      - jenkins-data:/var/jenkins_home:delegated
    ports:
      - 8080:8080
      - 50000:50000
    networks:
      ci-network:
    secrets:
      - jenkins-user
      - jenkins-pass

volumes:
  jenkins-data:

networks:
  ci-network:

secrets:
  jenkins-user:
    file: ./jenkins/jenkins-user.txt
  jenkins-pass:
    file: ./jenkins/jenkins-pass.txt
